/*
 * @Author       : LQ,jry
 * @Description  :
 * @version      : 4.0
 * @Date         : 2021-08-20 16:44:21
 * @LastAuthor   : jry
 * @lastTime     : 2024-08-28 14:20:58
 * @FilePath     : /uview-ultra/libs/config/props/navbar
 */
import color from '../../libs/config/color'

export default {
    // navbar 组件
    navbar: {
        safeAreaInsetTop: true,
        placeholder: true,
        fixed: true,
        border: false,
        leftIcon: 'arrow-left',
        leftText: '',
        rightText: '',
        rightIcon: '',
        title: '',
        bgColor: '',
        titleWidth: '400rpx',
        height: '44px',
		leftIconSize: 20,
		leftIconColor: color['mainColor'],
		autoBack: true,
		titleStyle: '',
        useBack: true,
        backText: '',
        operateText: '',
        operateIcon: '',
        titleColor: '',
        statusBarBgColor: '',
        transparent: false,
        bgImage: '',
        opacity: 1,
        statusbarInBody: false,
        theme: ''
    }
} as UTSJSONObject
